#!/bin/sh

installdir=

for argopt
do
	installdir=$argopt
done

if [ "x$installdir" == "x" ]; then
	echo "You probably want to specify the installation directory."
	echo ""
	echo "$0 /path/to/install/dir"

	exit
fi

./configure --installdir=$installdir --override-php --override-cpl

make && make install

mv create.sql /tmp/newsys.sql.tmp

make clean

mv /tmp/newsys.sql.tmp create.sql

echo "create.sql has been restored so that"
echo "you may use it"
echo
echo "be sure you remove it when finished"
