#!/bin/sh

installdir=

for argopt
do
	installdir=$argopt
done

if [ "x$installdir" == "x" ]; then
	echo "You probably want to specify the installation directory."
	echo ""
	echo "$0 /path/to/install/dir"

	exit
fi

cat >/tmp/newsys-auto <<EOF
user
pass
pass
key
EOF

./configure --installdir=$installdir --override-php --override-cpl < /tmp/newsys-auto

rm /tmp/newsys-auto

make uninstall && make clean

echo "newsys has been uninstalled from $installdir"
echo
echo "make sure you remove the RDBMS tables and such"
echo "to completely uninstall everything"
